language: node_js
node_js:
  - 8

install:
  - npm install -g lerna
  - lerna bootstrap

matrix:
  include:
    - name: "Core Pipeline"
      env: PACKAGE_LOCATION=packages/merquery-core
    - name: "CLI Pipeline"
      env: PACKAGE_LOCATION=packages/merquery-cli
    - name: "Sample Pipeline"
      env: PACKAGE_LOCATION=packages/merquery-sample

script:
  - cd $PACKAGE_LOCATION
  - npm test
